### ISSUE TITLE
Division doesn't work

### ISSUE THREAD

**Issue by td00** [ziulev/spotter#19]
```
Version: 0.0.4
OS: macOS Big Sur Version 11.1
Device: MacBook Air (Retina, 13-inch, 2018)

Installed via brew cask
```

When trying to divide in spotter, the app doesn't output anything.
![4 diveded by 2 (doens't work)](https://user-images.githubusercontent.com/10527500/106436889-ecfe3a00-6474-11eb-8a5d-94e1676cb81c.png)

Basic math functions working:
![2 times 3 (works just fine)](https://user-images.githubusercontent.com/10527500/106436975-0e5f2600-6475-11eb-959f-71237b3bbd00.png)

**Comment by niftylettuce** [comment]
Would love to see this added!

**Comment by ziulev** [comment]
[Solved 🚀](https://github.com/ziulev/spotter/commit/7a239ef89e96eecc2fc137d15755caecdd8be1aa)

**Comment by niftylettuce** [comment]
oh heck yeah!

**Comment by niftylettuce** [comment]
ping me when there's a new release if you don't mind!

**Comment by ziulev** [comment]
> ping me when there's a new release if you don't mind!

https://github.com/ziulev/spotter/releases/tag/0.0.5 🚀
https://github.com/Homebrew/homebrew-cask/pull/99867 🚀
