### ISSUE TITLE
Countdown isnt working.

### ISSUE THREAD

**Issue by td00** [ziulev/spotter#20]
```
Version: 0.0.4
OS: macOS Big Sur Version 11.1
Device: MacBook Air (Retina, 13-inch, 2018)

Installed via brew cask
```

When trying to set a timer for one minute (and possibly other times) the countdown never reaches zero.
(Attached Video:)
https://user-images.githubusercontent.com/10527500/106467574-25b20980-649d-11eb-85a9-1d7942749c31.mov

**Comment by ziulev** [comment]
[Solved 🚀](https://github.com/ziulev/spotter/commit/8b702dd33be5b37abf7d6b2dd64d5e5a9ecae0d0)
