### ISSUE TITLE
Open Finder with spotter

### ISSUE THREAD

**Issue by td00** [ziulev/spotter#21]
```
Version: 0.0.4
OS: macOS Big Sur Version 11.1
Device: MacBook Air (Retina, 13-inch, 2018)

Installed via brew cask
```
Finder isn't considered an App (as an Application stored in "/Applications" and is located here: "/System/Library/CoreServices".
To launch Finder.app via spotter and therefore use it as a full replacement of spotlight, this folder (or just the finder app) should be added to "appdir".

!["Finder.app" isn't executable via spotter](https://user-images.githubusercontent.com/10527500/106467776-67db4b00-649d-11eb-8513-8d9bebca2790.png)

**Comment by ziulev** [comment]
[Solved](https://github.com/ziulev/spotter/commit/b24ac9a7e9d91fdb927a2d7885eb228d3c3d8422)
