### ISSUE TITLE
When you click off spotter it should close it (similar to Alfred and Spotlight)

### ISSUE THREAD

**Issue by niftylettuce** [ziulev/spotter#22]
Right now it stays open unless you hit ESC.

**Comment by ziulev** [comment]
[Solved 🚀](https://github.com/ziulev/spotter/commit/a5b7fc162b7c49f0638caf9c7be5f9a77717510b)

**Comment by niftylettuce** [comment]
Yes!!!! 🙏  Thank you!

**Comment by niftylettuce** [comment]
Sponsoring you on GitHub.  I suggest others to do the same!!!!  Thank you!
