### ISSUE TITLE
Selecting the third item in a list of three matches hides the first

### ISSUE THREAD

**Issue by dnicolson** [ziulev/spotter#31]
I would expect that "Sublime Text" would still be visible when "Visual Studio Code" is selected.

![spotter](https://user-images.githubusercontent.com/2276355/108067300-dce37e80-7060-11eb-8364-9ff0467a82b2.gif)

spotter 0.0.5.

**Comment by ziulev** [comment]
[Solved here](https://github.com/ziulev/spotter/pull/32/commits/32ad0c9938dd7cc82cfc5ae86a6fc1e967f4e2e7)
