### ISSUE TITLE
Math is not correct (multiply/divide inaccurate)

### ISSUE THREAD

**Issue by niftylettuce** [ziulev/spotter#33]
(240000)*(1.4)
<img width="515" alt="Screen Shot 2021-02-20 at 9 54 34 PM" src="https://user-images.githubusercontent.com/523141/108615118-4eeff680-73c6-11eb-8158-3a63b46b6eef.png">

**Comment by ziulev** [comment]
Thank you for the report!

It has been fixed [here](https://github.com/ziulev/spotter/commit/cb71015ff1b09922d8c7f1fb7573c28c84beac1a)
[0.0.1-beta-2](https://github.com/ziulev/spotter/releases/tag/1.0.0-beta.2) includes the fix 🚀

**Comment by niftylettuce** [comment]
tested beta, works great!!! 🚀 🚀 🙏
