### ISSUE TITLE
Mathematical operations insert a comma for no reason

### ISSUE THREAD

**Issue by niftylettuce** [ziulev/spotter#34]
Please remove the comma!

Also make it so if you do `2+2=` it should output 4 (basically mirror Alfred please 👍 )
![Screen Shot 2021-02-22 at 2 18 11 PM](https://user-images.githubusercontent.com/523141/108765044-f3824d80-7518-11eb-978b-6fd49aa86575.png)

**Comment by ziulev** [comment]
[Check it out](https://github.com/ziulev/spotter/releases/tag/1.0.0-beta.3) 🚀

**Comment by niftylettuce** [comment]
👍
