### ISSUE TITLE
Mathematical chaining does not work

### ISSUE THREAD

**Issue by niftylettuce** [ziulev/spotter#35]
This should output the same that Alfred does, and it should also work so that if we type a trailing `=` it will output the value like Alfred does.

![Screen Shot 2021-02-25 at 3 26 06 PM](https://user-images.githubusercontent.com/523141/109219856-caaec200-777d-11eb-80c4-3e80e02ee564.png)

**Comment by ziulev** [comment]
The problem was that `0` was interpreted as `false` and did not show up in the results.
Fixed [here](https://github.com/ziulev/spotter/commit/c9ef1038af73c169243f24cf34116bce50664eac).
