### ISSUE TITLE
Download 0.0.5 contains wrong version number

### ISSUE THREAD

**Issue by suschizu** [ziulev/spotter#36]
Hello!

I've noticed that the latest stable download still contains 0.0.4 instead of 0.0.5 

![image](https://user-images.githubusercontent.com/16004333/109296681-0787c100-7831-11eb-9680-c42d68e838ae.png)

info.plist
```
CFBundleShortVersionString:
0.0.4

CFBundleVersion:
1
```

**Comment by ziulev** [comment]
It looks like I just forgot to update the version in info.plist
