### ISSUE TITLE
Some apps aren't showing in Spotter?

### ISSUE THREAD

**Issue by niftylettuce** [ziulev/spotter#37]
Nested apps inside folders in Applications dir aren't showing, at least for me.  Not sure if this is a Spotlight thing or is this a bug with Spotter not picking up nested apps?
![Screen Shot 2021-02-28 at 9 50 48 PM](https://user-images.githubusercontent.com/523141/109449853-1f1ca080-7a0f-11eb-910c-6adcc1d85400.png)

Appreciate all your hard work ❤️

**Comment by ziulev** [comment]
Implemented [here](https://github.com/ziulev/spotter/commit/b206067f6a3f19ffc0932f91f9fb9250f38dee52)

**Comment by niftylettuce** [comment]
v1.0.0 is broken again, apps not showing.  please test before releasing...
