### ISSUE TITLE
Is there any easy way or even a plugin to run a command on spotter as if I was on the command line?

### ISSUE THREAD

**Issue by jose** [ziulev/spotter#38]
Hi,

First, thanks for the awesome app.  👏

I've looking for an alternative app to [dmenu](https://tools.suckless.org/dmenu) for MacOS and I haven't found one good enough.  I was wondering whether there is a plugin to run a command on spotter as if I was on the command line...  For example, lets suppose I want to count number of files under `/tmp/`, I could go to the command line and type:
```
find /tmp/ -mindepth 1 -maxdepth 1 -type f | wc -l
```
but that process is very time consuming.  I always have a terminal window around, but still.  It would be nice to type that kind of one-line commands on spotter and then get the result on spotter as well.

--
Best,
Jose

**Comment by ziulev** [comment]
Hi @jose 👋
Please check [1.0.2-beta.3](https://github.com/ziulev/spotter/releases/tag/1.0.2-beta.3) release

https://user-images.githubusercontent.com/14956407/111920686-a26e6680-8a90-11eb-8baf-80400762142b.mov

*`t your_command <tab>`
* `term your_command <enter>`

**Comment by jose** [comment]
Hi @ziulev,

Thanks for implementing this.  Unfortunately, it does not seem to work on my computer... :-/

First, when I'm in spotter's mode 'Execute and copy result to clipboard' for every character I write there is a `syntax error`:
```
bash-3.2$ ./spotter
/bin/bash: -c: line 1: syntax error: unexpected end of file

/bin/bash: -c: line 1: syntax error: unexpected end of file

/bin/bash: -c: line 1: syntax error: unexpected end of file

/bin/bash: -c: line 1: syntax error: unexpected end of file

/bin/bash: -c: line 1: syntax error: unexpected end of file
```

Second, spotter freezes as soon I hit enter.  Independently of writing a correct or incorrect bash command.


--
Best,
Jose

**Comment by ziulev** [comment]
It looks like your command is invalid

https://user-images.githubusercontent.com/14956407/114020710-2b96e300-9870-11eb-8b0c-8941152247ea.mov
