### ISSUE TITLE
Cannot use mouse to click on results, must be navigated to with arrow keys

### ISSUE THREAD

**Issue by niftylettuce** [ziulev/spotter#39]
Pretty sure this is a bug, on macOS Big Sur I can't click on results, I have to navigate with arrow keys up and down and hit enter.

![Screen Shot 2021-03-03 at 3 43 49 PM](https://user-images.githubusercontent.com/523141/109876381-5a011d00-7c37-11eb-9114-ed1460c3014d.png)

**Comment by ziulev** [comment]
Solved [here](https://github.com/ziulev/spotter/commit/f9029249cb32c8cf339cabc9d04d49a2172867c9)

**Comment by niftylettuce** [comment]
Thank you @ziulev just ping me of a new release?

**Comment by ziulev** [comment]
@niftylettuce https://github.com/ziulev/spotter/releases/tag/1.0.0-beta.4 🚀
