### ISSUE TITLE
bug in latest beta (when you click on a result, Spotter app closes)

### ISSUE THREAD

**Issue by niftylettuce** [ziulev/spotter#40]
e.g. when I click on the calculator result, the Spotter app will close

![Screen Shot 2021-03-04 at 10 55 54 AM](https://user-images.githubusercontent.com/523141/109999878-51145800-7cd8-11eb-8651-76376341867b.png)

Also there is another bug - if I type the `=` equal sign, it should take the answer and replace the input area with the answer (like Alfred does).  so if I type `2+2` the moment I type `=` sign afterwards, e.g. typing `2+2=`, the input should change to `4`.

**Comment by niftylettuce** [comment]
Fixed yet? @ziulev

**Comment by ziulev** [comment]
The click issue has been fixed, yes.

**Comment by niftylettuce** [comment]
Thanks!  Will try it out 👍
