### ISSUE TITLE
Apps not showing in latest version

### ISSUE THREAD

**Issue by niftylettuce** [ziulev/spotter#41]
<img width="546" alt="Screen Shot 2021-03-04 at 10 19 45 PM" src="https://user-images.githubusercontent.com/523141/110066738-c5321880-7d37-11eb-8f43-c82e198349ef.png">

**Comment by ziulev** [comment]
[Fixed](https://github.com/ziulev/spotter/commit/29707015a1b4e17d561e51b4a4bea159de3cd629) 🚀

**Comment by niftylettuce** [comment]
v1.0.0 is broken again, apps not showing.  please test before releasing...

**Comment by ziulev** [comment]
![image](https://user-images.githubusercontent.com/14956407/111129025-e552aa80-8575-11eb-8954-53b38076daef.png)
Can't reproduce 🤔

**Comment by larswittenberg** [comment]
Same here. No Apps.
Installation via Homebrew

<img width="882" alt="20210318_58zk6" src="https://user-images.githubusercontent.com/1742089/111594066-e2042c80-87ca-11eb-8f81-804a61a37e60.png">

**Comment by ziulev** [comment]
> Same here. No Apps.
> Installation via Homebrew
> 
> <img alt="20210318_58zk6" width="882" src="https://user-images.githubusercontent.com/1742089/111594066-e2042c80-87ca-11eb-8f81-804a61a37e60.png">

Big Sur?
Because spotter only supports Big Sur

**Comment by larswittenberg** [comment]
> > Same here. No Apps.
> > Installation via Homebrew
> 
> Big Sur?
> Because spotter only supports Big Sur

yes. Dig Sur 11.2.3.

After the installation I ran `xattr -cr /Applications/spotter.app`, otherwise I could not start the app at all.

**Comment by arturoacevedob** [comment]
Same here. No apps.

**Comment by ziulev** [comment]
Guys, I cannot reproduce the issue on both my laptops.
Could you please check [this build](https://github.com/ziulev/spotter/releases/tag/1.0.1-beta.1)?

**Comment by larswittenberg** [comment]
> Guys, I cannot reproduce the issue on both my laptops.
> Could you please check [this build](https://github.com/ziulev/spotter/releases/tag/1.0.1-beta.1)?

yeah, this works. Downloaded the .dmg and replaced the spotter app.

**Comment by ziulev** [comment]
1.0.1 released
https://github.com/Homebrew/homebrew-cask/pull/101427
https://github.com/ziulev/spotter/releases/tag/1.0.1

**Comment by niftylettuce** [comment]
confirmed  fixed!
