### ISSUE TITLE
Calculation bug (v1.0.0)

### ISSUE THREAD

**Issue by niftylettuce** [ziulev/spotter#44]
<img width="712" alt="Screen Shot 2021-03-15 at 2 53 22 AM" src="https://user-images.githubusercontent.com/523141/111120654-a30b7800-8539-11eb-8373-a611180a8536.png">

**Comment by ziulev** [comment]
Should work since [1.0.2-beta.2](https://github.com/ziulev/spotter/releases/tag/1.0.2-beta.2) 🚀
