### ISSUE TITLE
When you type `=` after calc operation, it should replace input in Spotter with the value (v1.0.0)

### ISSUE THREAD

**Issue by niftylettuce** [ziulev/spotter#45]
Example: If I type `2+2`, the moment I type the `=` sign after, e.g. `2+2=4`, then the value of Spotter input should be replaced with `4` completely.  This is the same handy behavior that Alfred and Spotlight have I believe, or at least I know Alfred does!  It has saved me so much time in the past and would love to see this built-in to Spotter.

<img width="712" alt="Screen Shot 2021-03-15 at 2 55 18 AM" src="https://user-images.githubusercontent.com/523141/111120842-e2d25f80-8539-11eb-9386-fb8c953706e9.png">

**Comment by ziulev** [comment]
Hey @niftylettuce 👋
Check [1.0.2-beta.1](https://github.com/ziulev/spotter/releases/tag/1.0.2-beta.1) please

**Comment by niftylettuce** [comment]
amazing!
