### ISSUE TITLE
No search results *Major Bug* (v1.0.0)

### ISSUE THREAD

**Issue by niftylettuce** [ziulev/spotter#46]
The latest stable release v1.0.0 has inaccurate search results, no applications nor nested items e.g. Photoshop/Illustrator inside a folder in Applications directory are showing.  No search results 😦

**Comment by niftylettuce** [comment]
See https://github.com/ziulev/spotter/issues/41 and https://github.com/ziulev/spotter/issues/37

**Comment by ziulev** [comment]
![image](https://user-images.githubusercontent.com/14956407/111129419-5a25e480-8576-11eb-8b05-9f146325fe21.png)
Can't reproduce

**Comment by niftylettuce** [comment]
The issue is that in previous versions, even if you had Spotlight completely disabled, the search results would still work.  You change the lookup logic and now it _requires_ Spotlight to work.

**Comment by ziulev** [comment]
Hm no, spotter is not dependent on spotlight in any way

**Comment by niftylettuce** [comment]
Oh - well the only way I can get search results to show is by using the older stable version 😦

**Comment by niftylettuce** [comment]
![Uploading Screen Shot 2021-03-16 at 8.40.22 AM.png…]()

**Comment by ziulev** [comment]
How did you install the latest one? homebrew or dmg?

**Comment by niftylettuce** [comment]
dmg

**Comment by niftylettuce** [comment]
Can you ping me once new release available?
