### ISSUE TITLE
release is damaged

### ISSUE THREAD

**Issue by koin612** [ziulev/spotter#47]
Hello,

I downloaded spotter from brew with `brew install --cask spotter` and also tried to download release 1.0.0 here from github.
When I open spotter it opens a dialog:

![Screen Shot 2021-03-15 at 18 32 20](https://user-images.githubusercontent.com/8482235/111195669-c88d9580-85bc-11eb-91aa-cbfb7502e9c6.png)

The steps listed under Troubleshoot, doesn't help.

- Big Sur 11.2.3

Edit:
- Version 1.0.0-beta.4 works

**Comment by bsantschi** [comment]
1. Open Terminal
2. `xattr -cr /Applications/spotter.app`
3. Enjoy
