### ISSUE TITLE
Dictionary plugin 📚

### ISSUE THREAD

**Issue by relikd** [ziulev/spotter#50]
Would love to see a dictionary lookup similar to Spotlight. But unlike Spotlight, one that actually works and respects my own dictionary file. Spotlight always searches in all dictionaries instead of the one I would like it use. Oh, and would be nice if it would use system and user dictionaries (`~/Library/Dictionaries/`).

**Comment by ziulev** [comment]
Hey @relikd 
Would love to see PR 🙂❤️

Closing for now since it doesn't look like a high priority at the moment.
