### ISSUE TITLE
Visual glitch in Catalina

### ISSUE THREAD

**Issue by relikd** [ziulev/spotter#51]
The screenshot shows a dark gray color (dark mode), however the actual color was transparent and showing the background color instead. Only the shadow border indicated that something is wrong. Also, during that time it appeared to be lagging. At some point the menu bar icon did disappear while the app was still running. And clicking the three dots to show more results was also not possible. After a relaunch of the app the three dots were clickable again, however the transparent window frame is still omnipresent.

![screen](https://user-images.githubusercontent.com/1321720/111552995-c0cc1d80-8783-11eb-9cbc-edd031a8ef09.png)

**Comment by ziulev** [comment]
Hey @relikd!
Thank you for the report, but at the moment Spotter only supports Big Sur

**Comment by relikd** [comment]
too bad, because from what I've seen the functionality seems to work fine. Just the UI thing. (and maybe performace issues, but I haven't looked in too deep). But anyway, still love the project ;)

**Comment by ziulev** [comment]
Glad to hear it 🍀
Would love to review your PR 🙂

**Comment by relikd** [comment]
> Would love to review your PR 🙂

uff, I nearly ran for it. But the dependency tree is killing me. Now I am not even sure if I am comfortable running it. (sorry, security background).

**Comment by ziulev** [comment]
No problem, if have any questions just let me know 🚀
