### ISSUE TITLE
Wrong version number in latest release

### ISSUE THREAD

**Issue by suschizu** [ziulev/spotter#54]
Hello - I just noticed that the 1.0.1 download contains version 1.0.0 instead of 1.0.1

info.plist:
```
	<key>CFBundleShortVersionString</key>
	<string>1.0.0</string>
…
	<key>CFBundleVersion</key>
	<string>1</string>
```

<img width="328" alt="Screen Shot 2021-03-20 at 19 25 51" src="https://user-images.githubusercontent.com/16004333/111881910-0884bc00-89b3-11eb-94da-8a0f863b5dda.png">

**Comment by ziulev** [comment]
Hey @suschizu 👋
Thank you for the report.
It looks like again I forgot to update the version in info.plist 🙂
