### ISSUE TITLE
Empty settings

### ISSUE THREAD

**Issue by MertSafter** [ziulev/spotter#55]
Hi,

I previously installed spotter and removed some settings. After a while, I wanted to use it again and reinstalled it, but now all settings but hotkey are gone. How can I restore them?

![image](https://user-images.githubusercontent.com/69803294/112833740-7148f400-9097-11eb-9678-333ab3e3d1e1.png)

**Comment by MertSafter** [comment]
Any update?

**Comment by ziulev** [comment]
Sorry for the long answer.
Please check [1.0.3 release](https://github.com/ziulev/spotter/releases/tag/1.0.3)
