### ISSUE TITLE
Chrome Applications didn't appear in search

### ISSUE THREAD

**Issue by muratangin187** [ziulev/spotter#56]
I have installed Youtube Music as a web application via Chrome. It appears in both the spotlight search and applications menu but it didn't be indexed by a spotter.

**Comment by ziulev** [comment]
Hey @muratangin187 👋
Check [1.0.2-beta.4](https://github.com/ziulev/spotter/releases/tag/1.0.2-beta.4) please

**Comment by muratangin187** [comment]
ı checked the beta and it works pretty fine, but there is a one little issue about thumbnail icon of apps in user path. For example youtube music app shown as a white default file icon
