### ISSUE TITLE
Support alternative App locations as well as Exclusions

### ISSUE THREAD

**Issue by exiva** [ziulev/spotter#57]
Currently the Applications section only searches specific hardcoded paths for Applications 
see: https://github.com/ziulev/spotter/blob/7e71d72c4da230d4f1af896a6d89f36df699b180/src/core/helpers.ts#L49-L54

Supporting at least `~/Applications` would be an improvement. However, it should look everywhere like Spotlight and Alfred do, and have exclude paths to ignore certain apps.

**Comment by exiva** [comment]
This may also fix #56

**Comment by ziulev** [comment]
@exiva check [1.0.2-beta.4](https://github.com/ziulev/spotter/releases/tag/1.0.2-beta.4) please

**Comment by exiva** [comment]
@ziulev doesn't seem to be working, not seeing anything being picked up in ~/Applications I think maybe the wrong build got uploaded? The spotify and terminal plugins aren't in `Contents/Resources/assets/src/plugins` 
<img width="240" alt="Screen Shot 2021-04-08 at 12 47 44 PM" src="https://user-images.githubusercontent.com/56931/114065394-9fcd8880-9868-11eb-942e-47d26a931497.png">

🤔

**Comment by ziulev** [comment]
Closing here?

**Comment by exiva** [comment]
Perhaps having paths outside of the default `/Applications` be user configurable would be beneficial?

**Comment by ziulev** [comment]
Makes sense, but I would prefer to get back to this question in the context of [another task about settings](https://github.com/ziulev/spotter/issues/29).

**Comment by exiva** [comment]
Sounds good. Didn't know it was there too. Closing now.
