### ISSUE TITLE
Spotter 1.0.2 does not launch other apps

### ISSUE THREAD

**Issue by baggiponte** [ziulev/spotter#59]
Hello there,

yesterday I updated Spotter to `1.0.2` using Homebrew and since then no option comes out when I type `<app-name>`. Until the last update, I could launch any app from there (as Alfred does). Is this happening to anyone else?

Thank you for your job!

**Comment by td00** [comment]
Same issue, after auto-upgrading.

**Comment by ziulev** [comment]
Does reinstalling from scratch help?

**Comment by td00** [comment]
Nope.
Removed App & removed all files created and reinstalled via brew cask.
macOS 11.2.3 on a x64 Intel based System

**Comment by ziulev** [comment]
Please check [1.0.3 release](https://github.com/ziulev/spotter/releases/tag/1.0.3)

**Comment by td00** [comment]
Doens't fixed it for me. (Not sure what should've fixed it.. It only changes some stuff in the README (https://github.com/ziulev/spotter/compare/1.0.2...1.0.3)

Is there maybe something missing in the release?

**Comment by exiva** [comment]
Still experiencing it as well, no apps populate regardless of where they are located. Maybe related to changes for #57?

**Comment by exiva** [comment]
I found the issue @ziulev

I did not have the directory `/Users/$USER/Applications/Chrome Apps.localized` since I don't use chrome. Once i made a `Chrome Apps.localized` folder and restarted  everything came back. 

https://github.com/ziulev/spotter/blob/0ecfc79219041e9eff49d003c9bfcb3185c15d69/src/core/helpers.ts#L89

**Comment by ziulev** [comment]
Thank you @exiva 🚀
Please check https://github.com/ziulev/spotter/releases/tag/1.0.4

**Comment by exiva** [comment]
@ziulev seems to work now, Was able to delete Chrome Apps.localized and functionality remains 👍

**Comment by baggiponte** [comment]
Hi there! Thank you for the contributions and thank you @ziulev for dealing with the problem. I guess I will close this once I can open Spotter (see #61) and see for myself?
