### ISSUE TITLE
App Icons Missing for apps in ~/Applications

### ISSUE THREAD

**Issue by exiva** [ziulev/spotter#60]
If an application resides in `~/Applications`, it will show a blank document icon for the Apps icon

<img width="650" alt="Screen Shot 2021-04-22 at 5 18 05 PM" src="https://user-images.githubusercontent.com/56931/115786361-b5759e80-a38e-11eb-83a3-4eff759ac4d6.png">

But Applications in `/Applications` show up fine

<img width="637" alt="Screen Shot 2021-04-22 at 5 18 35 PM" src="https://user-images.githubusercontent.com/56931/115786413-c7574180-a38e-11eb-93ed-eb08349da89c.png">

Spotter 1.0.3 & 1.0.4, MacOS Big Sur 11.2.3

**Comment by ziulev** [comment]
Please check https://github.com/ziulev/spotter/releases/tag/1.0.5 🚀

**Comment by exiva** [comment]
Fixed. Thanks for fast update @ziulev
