### ISSUE TITLE
Spotter 1.0.4 does not launch neither with Homebrew nor with regular download

### ISSUE THREAD

**Issue by baggiponte** [ziulev/spotter#61]
Hi there, 

I am having some problems installing [Spotter 1.0.4](https://github.com/ziulev/spotter/releases/tag/1.0.4) on macOS BigSur 11.2.3, both with Homebrew and regular download of the `.dmg` file from the link above. See attached pics as a reference:

![spotter_dmg_damaged](https://user-images.githubusercontent.com/57922983/115851062-d5f13780-a426-11eb-8c69-bb23bd2bab74.png)
![spotter_homebrew_damaged](https://user-images.githubusercontent.com/57922983/115851068-d7226480-a426-11eb-98c8-85c0b1df5100.png)

**Comment by ziulev** [comment]
Does that help? https://github.com/ziulev/spotter#spotterapp-is-damaged-and-cant-be-opened

**Comment by baggiponte** [comment]
Oh yeah, problem solved, thanks!
