### ISSUE TITLE
🖌️ Theme Support

### ISSUE THREAD

**Issue by exiva** [ziulev/spotter#65]
Having theme support would expand customizability to fit everyones liking.

**Comment by ziulev** [comment]
Hey @exiva 👋

Thank you for the issue and sorry it took me so long.


I just created a [release](https://github.com/ziulev/spotter/releases/tag/2.0.0-beta.10) with themes support

Just type `themes <tab>` and choose a theme
If you want to create a custom one: `themes <tab> #1c2128,#adbac7,#2d333b,#ffffff,#0f60cf,#fefefe
`

Colors:
1. background
2. text
3. activeOptionBackground
4. activeOptionText
5. hoveredOptionBackground
6. hoveredOptionText
