### ISSUE TITLE
Mouse input issues

### ISSUE THREAD

**Issue by exiva** [ziulev/spotter#67]
When you do a search, using the mouse to click on an item will open the currently highlighted item. Even though the right item you click on turns blue like it did register. It would also be nice for it to move the highlighted item as you hover over the cell.

**Comment by ziulev** [comment]
Hey @exiva 
Thank you for the report 🙏

Please check [https://github.com/ziulev/spotter/releases/tag/1.0.7](1.0.7 release)

**Comment by exiva** [comment]
1.0.7 will open whatever you click on, but highlighting whatever is being hovered over does not happen still.

**Comment by ziulev** [comment]
Hey @exiva 👋
It has been fixed in https://github.com/ziulev/spotter/releases/tag/2.0.0-beta.11
![123](https://user-images.githubusercontent.com/14956407/146057127-981cf001-1807-453c-ab14-4930aa73250d.gif)

Please test 🙏
