### ISSUE TITLE
Support for Applications installed with JetBrains Toolbox.

### ISSUE THREAD

**Issue by galambosmisi** [ziulev/spotter#68]

**Comment by Zaitam** [comment]
Jetbrains uses a launcher stored in `~/Applications/JetBrains Toolbox`
If you want the real app, it's stored in `~/Library/Application Support/JetBrains/Toolbox/apps`.

**Comment by Zaitam** [comment]
This should be fix with #84

**Comment by ziulev** [comment]
Hey @galambosmisi ! Does it work now in the [latest versions](https://github.com/ziulev/spotter/releases/tag/2.0.0-beta.18)?
