### ISSUE TITLE
Opening files in spotter

### ISSUE THREAD

**Issue by Jefin10** [ziulev/spotter#71]
Hey! I'm new to spotter, and I am really loving the app. I don't know anything about coding, but I was able to get the app up and running. One question though: does spotter let me search for files? I don't seem to be able to do so.

Also, is there a quicker way to open Spotter settings? I've been doing it by setting a timer and click on the timer icon and then accessing settings. I'm sure there is a better way.

**Comment by ziulev** [comment]
Hey @Jefin10 and welcome 👋

At the moment you can't search throw files.
And you can quickly open settings just by opening spotter query panel and pressing `cmd + ,`

**Comment by Jefin10** [comment]
Got it! Will searching through files be a feature in the future?

**Comment by ziulev** [comment]
Yeah,
at least I'm planing to do it.

Closing for now.
