### ISSUE TITLE
Auto launch cannot be saved when checked

### ISSUE THREAD

**Issue by liby** [ziulev/spotter#76]
1. Auto launch cannot be saved when checked
2. The setting window is always at the top, affecting other programs

https://user-images.githubusercontent.com/38807139/131978606-93e80196-8266-4873-90db-a2eaa84ce7cd.mp4

**Comment by ziulev** [comment]
Hey @liby

Thank you for the issue.
I'm going to take a look after #74 🙂

**Comment by ziulev** [comment]
Hey @liby  👋

I just created a release with the fix. Could you take a look?
https://github.com/ziulev/spotter/releases/tag/2.0.0-beta.11

**Comment by liby** [comment]
Thank you for telling me the news. I'll try it out and give feedback if I run into issues.

**Comment by ziulev** [comment]
Closing for now. Feel free to reopen 🚀
