### ISSUE TITLE
Mojave / 10.14 build of latest beta?

### ISSUE THREAD

**Issue by sunrez** [ziulev/spotter#78]
Hi,

Is it possible to get a build of the latest Spotter that can run on 10.14?  It seems the min version is set to 10.15 .

I downloaded the latest source code and tried to build it myself with Xcode 11.1 but after some digging realized the build process needs Cocopods, npm, etc which my Mac isn't currently set up with.

Thank you!

**Comment by Zaitam** [comment]
Sorry for the delayed response. Been testing out for a MacOS 10.15 and lower version however It would require changing how the window is generated or rendered. I been unable to try it in 10.14 specifically but made some test in Catalina.
