### ISSUE TITLE
Software Needs to be Updated Dialogue

### ISSUE THREAD

**Issue by Alpheron** [ziulev/spotter#79]
Hi, I've been using Spotter for quite some time now. However, when I had upgraded to Big Sur, I suddenly started receiving this message:

![Screen Shot 2021-11-15 at 5 57 07 PM](https://user-images.githubusercontent.com/25261413/141881832-a94f4830-05bb-4215-9cca-ef3dc29187dd.png)

Is there a particular fix for this on my end, or is this something wrong with the Spotter library?  

EDIT: I have tried the troubleshooting steps at the very bottom but it still is not working.

**Comment by ziulev** [comment]
Hey @Alpheron 👋

Could you try the latest beta versions https://github.com/ziulev/spotter/releases ?

**Comment by Alpheron** [comment]
Trying with the beta works! I cannot seem to authorize my spotify or search for any files however. Is file searching not implemented or is it just not working for me?

**Comment by ziulev** [comment]
Sounds like a bug. Could you share more details please?

**Comment by Alpheron** [comment]
That results in something like the following:

![Screen Shot 2021-11-28 at 12 53 33 PM](https://user-images.githubusercontent.com/25261413/143785604-8c754656-c559-4cdb-8242-585ea03c7c07.png)

**Comment by ziulev** [comment]
Ok, try to close and open spotter. It should help. I'll fix it in the next release.

I'm closing this issue for now. Feel free to reopen if still have the open issue

**Comment by Alpheron** [comment]
The issue still appears even after closing and reopening. Is there a way to print some sort of debugging information?

**Comment by ziulev** [comment]
Please wait a little bit more, I am still working on [core](https://github.com/spotter-application/spotter-core)
