### ISSUE TITLE
Im not sure if I have installed it correctly?

### ISSUE THREAD

**Issue by MendesA1994** [ziulev/spotter#83]
Good Evening, 
I just downloaded spotter and it's not allowing me to search anything other than plugins, and won't compile options for the plugins. I installed it from the DMG file, but I'm not too sure what I'm doing wrong in the set-up of spotter.. would it be possible to get some assistance?

https://user-images.githubusercontent.com/67050506/145829418-642b7b78-53cd-444d-823c-10ed8bb6d2a7.mov

**Comment by MendesA1994** [comment]
My apologies for being a nuisance, I've just tried that and I cant see its feedback behaviour.

https://user-images.githubusercontent.com/67050506/145837301-965e4805-5058-4fc9-a21d-a611231c575d.mov

**Comment by Zaitam** [comment]
This command should be installed by terminal.app, found under Utilities folder.

**Comment by ziulev** [comment]
Yeah, right, you need to execute the command in your terminal
I'll implement the easiest way to do it later

**Comment by MendesA1994** [comment]
Im sorry - npm isn't working on mine

<img width="581" alt="Screen Shot 2021-12-14 at 05 05 17" src="https://user-images.githubusercontent.com/67050506/145872640-458a29b3-b1c9-4fe1-8f00-3b062af3f4b4.png">

**Comment by Zaitam** [comment]
I think spotter is expected to install **Homebrew** and **NodeJS** (with npm). However as it hasn't done it try:

(To install Brew and Node)
`/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" && brew install node`

(To install just Node)
Head over to  [Nodejs.org](https://nodejs.org/) and download the [LTS version](https://nodejs.org/dist/v16.13.1/node-v16.13.1.pkg) and follow the steps presented by the installer.

If this works, please close the issue.
(Remember to re-run `npm i -g @spotter-app/applications-plugin@1.9.2` in the terminal after this)

**Comment by MendesA1994** [comment]
Thank you so much guys, I really appreciate it: @Zaitam @ziulev

**Comment by ziulev** [comment]
Hey @MendesA1994
Just released new beta with preinstall plugins feature https://github.com/ziulev/spotter/releases/tag/2.0.0-beta.11

🚀
