### ISSUE TITLE
Spotter can't find installed plugins?

### ISSUE THREAD

**Issue by Gravitonic** [ziulev/spotter#87]
Hi, not sure if this is a node issue or a Spotter issue, or if I'm just doing something wrong, but I can't seem to get the Spotter app to find the plugins I install.

For example I used `npm i -g @spotter-app/applications-plugin` and when I check `npm list -g` in my terminal, `@spotter-app/applications-plugin@1.11.0` is included in the list (I tried the spotify one too):
```
├── @spotter-app/applications-plugin@1.11.0
├── @spotter-app/spotify-plugin@1.11.0
├── corepack@0.10.0
├── npm@8.3.0
└── yarn@1.22.17
```

But when I open the Spotter app, none of the plugins show as installed
![image](https://user-images.githubusercontent.com/29341383/147036683-14a9e481-70ce-4ed9-8c71-a03a9496c16f.png)

**Comment by ziulev** [comment]
Hey @Gravitonic 
Thank you for the issue 🚀

Could you check this release please https://github.com/ziulev/spotter/releases/tag/2.0.0-beta.18
