### ISSUE TITLE
Type `plugins <tab>` not working

### ISSUE THREAD

**Issue by liby** [ziulev/spotter#88]
https://user-images.githubusercontent.com/38807139/154401164-a42e21f3-6d66-48d1-9409-4efced2b826a.mp4

**Comment by ziulev** [comment]
Hey @liby 
Thank you for the report

Do you use https://github.com/ziulev/spotter/releases/tag/2.0.0-beta.18 ?

**Comment by liby** [comment]
@ziulev 

Oh, it doesn't look like it. I'll download the latest version and try again.
```
❯ brew info spotter
spotter: 1.0.7
https://github.com/spotter-application/spotter
/usr/local/Caskroom/spotter/1.0.7 (121B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/spotter.rb
==> Name
Spotter
==> Description
Productivity tool to launch everything
==> Artifacts
spotter.app (App)
==> Analytics
install: 42 (30 days), 132 (90 days), 881 (365 days)
```
